server:
  port: 8023
upload:
  file-space: C:\Project\mywork\newjiaoyu\resource
appsetings:
  version-key : 1.10.2
  domain : 182.92.189.147
spring:
  #    国际化文件位置
  messages.basename: i18n/message

# 本地redis
  redis.host : 127.0.0.1
  redis.port : 6379
  redis.database : 0
  #连接池最大连接数（使用负值表示没有限制）
  redis.jedis.pool.max-active : 50
  redis.jedis.pool.max-wait : 3000
  redis.jedis.pool.max-idle : 20
  redis.jedis.pool.min-idle : 2
  redis.timeout : 5000

  datasource:

    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthclubs?useSSL=false&serverTimezone=UTC
    username: root
    driverclassname: com.mysql.jdbc.Driver
mybatis:
 mapperLocations: classpath*:mapper/*.xml
logging:
  level.root:  com.healthclubs.pengke
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
