server:
  port: 8023
upload:
  file-space: D:\wwwroot\resource
appsetings:
  version-key : 1.10.2
  domain : 182.92.189.147
spring:
  #    国际化文件位置
  messages.basename: i18n/message

  # 服务器
  #Redis服务器地址
  redis.host : 182.92.189.147

#密码
  redis.password : test123

  #Redis服务器连接端口
  redis.port : 6379
  #Redis数据库索引（默认为0）
  redis.database : 3
  #连接池最大连接数（使用负值表示没有限制）
  redis.jedis.pool.max-active : 50
  #连接池最大阻塞等待时间（使用负值表示没有限制）
  redis.jedis.pool.max-wait : 1000
  #连接池中的最大空闲连接
  redis.jedis.pool.max-idle : 20
  #连接池中的最小空闲连接
  redis.jedis.pool.min-idle : 3
  #连接超时时间（毫秒）
  redis.timeout : 5000

  datasource:

    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthclubs?useSSL=false&serverTimezone=UTC
    username: root
    driverclassname: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath*:mapper/*.xml
logging:
  level.root:  com.healthclubs.pengke
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
